version: '3'
services:
  app:
    build: .
    env_file: .env
    restart: always
    expose:
    - 8080
    ports:
    - 8080:8080
    links:
    - database
  database:
    image: mysql
    env_file: .env
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_DATABASE=${DATABASE_NAME}
    - MYSQL_USER=${DATABASE_USER}
    - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
