version: '3.3'
services:
  app:
    build: .
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - mysql
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=app

